pidfile /tmp/wisp-udhcpd.pid
start 192.168.50.100
end 192.168.50.199
interface br0
remaining yes
lease_file /tmp/wisp-udhcpd.leases
option subnet 255.255.255.0
option router 192.168.50.1
option dns 192.168.157.245
option lease 600
